clone:
  git:
    image: plugins/git
    tags: true

pipeline:
  test1:
    image: mhart/alpine-node:9.1.0
    group: testing
    commands:
      - mkdir /etc/aaaa/bbbb/cccc

  test2:
    image: mhart/alpine-node:9.1.0
    group: testing
    commands:
      - mkdir /etc/aaaa/bbbb/cccc
    when:
      branch: [ develop ]

  test3:
    image: mhart/alpine-node:9.1.0
    group: testing
    commands:
      - mkdir /etc/aaaa/bbbb/cccc
    when:
      status: [ failure ]

  # test2:
  #   image: appleboy/golang-testing
  #   group: testing
  #   secrets: [ test46, readme ]
  #   commands:
  #     - echo "golang"
  #     - echo $TEST46
  #     - echo $README

# services:
#   redis-test:
#     image: redis
